### ISSUE TITLE
浏览器内运行脚本的时候，可以加入访问quicker内的变量的功能

### ISSUE THREAD

**Issue by zhongbr** [cuiliang/QuickerConnectorExtension#1]
在浏览器的插件里运行脚本的时候，如果可以访问和改变到quicker内定义的变量，那么可玩性会更高，希望作者可以加入。

**Comment by cuiliang** [comment]
这个目前不可行。因为在quicker和浏览器之间是需要跨进程的，通信使用文本传递方式。
只能把quicker变量的内容插值到脚本里。
