### ISSUE TITLE
插件提示无法连接 quicker，但脚本可用

### ISSUE THREAD

**Issue by Chandler-Lu** [cuiliang/QuickerConnectorExtension#4]
![image](https://user-images.githubusercontent.com/18322610/152456158-08db181f-d1fb-4d8a-a7ee-e310a4b74775.png)
![image](https://user-images.githubusercontent.com/18322610/152456177-d5bdfc96-ca12-4f85-bc34-bd3459cb6429.png)
![image](https://user-images.githubusercontent.com/18322610/152456212-dfc2c38d-142d-4095-8d3a-a6be5e81a1ba.png)

但要求 quicker 插件的脚本，如 https://getquicker.net/Sharedaction?code=11a8a7f4-44c9-41e7-b496-08d82face005 可用。已经尝试在 quicker 内`修复与浏览器扩展的连接`，依然提示未连接。感觉像是显示问题

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  这里下载1.29.0 版本

**Comment by Chandler-Lu** [comment]
原来更新了，谢谢！
