### ISSUE TITLE
打开网站填参数就会返回失败

### ISSUE THREAD

**Issue by 627992512** [cuiliang/QuickerConnectorExtension#6]
是创建窗口的参数改了吗
![image](https://user-images.githubusercontent.com/57834276/187738140-70f839f5-b540-4192-a068-e189c632c3dc.png)
![image](https://user-images.githubusercontent.com/57834276/187738171-f48dc189-a832-41aa-9b3d-d53cb5550561.png)

**Comment by 627992512** [comment]
破案了，参数要加引号，建议重新编辑一下这个文档
https://getquicker.net/KC/Help/Doc/chromecontrol
![image](https://user-images.githubusercontent.com/57834276/187739565-be1946a1-24e3-4f01-ab9d-659beff271a3.png)

**Comment by cuiliang** [comment]
确实这里错了，已修改，谢谢！
